### ISSUE TITLE
Adapter unable to connect if password contains special characters

### ISSUE THREAD

**Issue by ekoHamburg** [DrozmotiX/ioBroker.discovergy#117]
I had a password for Discovergy containing characters like @ \ # etc. The adapter complains:
discovergy.0 (7708) Connection_Failed at meter indication run, check your credentials !

After changing to a password with numbers and alphabetical characters only logon was possible.

**Comment by sirjojo69** [comment]
same here.... Encoding?

**Comment by DutchmanNL** [comment]
change password encryption to native JS-controller implementation you may need to re-enter you password from version 0.5.7
