### ISSUE TITLE
Missing values in iobrpker logfile

### ISSUE THREAD

**Issue by sebatro** [DrozmotiX/ioBroker.discovergy#198]
**Describe the bug**  
I get error message in ioBroker Log

**To Reproduce**  
see logfile

**Expected behavior**  
Read all data from meter

**Screenshots & Logfiles**  
[iobroker.2021-03-29.log](https://github.com/DrozmotiX/ioBroker.discovergy/files/6231462/iobroker.2021-03-29.log)

**Versions:**  
 - Adapter version: 0.5.4
 - JS-Controller version: 3.2.16
 - Node version: 14.15.4
 - Operating system: Ubuntu 20.04

**Additional context**  
Got new Discovergy meter right these days

**Comment by supabogun** [comment]
I've had the same problem.
This is fixed in version 0.5.7 (2021-03-19), which isn't in stable right now.
You can install it manually or wait until @DutchmanNL pushes it to stable (i couldn't find any problems).

**Comment by DutchmanNL** [comment]
0.5.7 is indeed in latest for 12 days al will be published soon to stable.

I see that 17% of all user already have 0.5.7 (beta) and I don't get issue in sentry or additional issue on git so looks good,  give it time.  to the weekend. Will keep the issue open until it's published


0.5.7 | 53 | 17.32%
-- | -- | --
0.5.6 | 3 | 0.98%
0.5.4 | 149 | 48.69%
0.5.0 | 89 | 29.08%
0.4.9 | 4 | 1.31%
0.4.0 | 8 | 2.61%



<img width="816" alt="Schermafbeelding 2021-03-31 om 10 29 18" src="https://user-images.githubusercontent.com/7318445/113114749-f48b5680-920b-11eb-958a-655f55ff2e1b.png">

**Comment by DutchmanNL** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/1443
