### ISSUE TITLE
energyProducer506 unknown energyProducer507 unknown

### ISSUE THREAD

**Issue by Illaren** [DrozmotiX/ioBroker.discovergy#200]
Hi There i have a little Problem,

the logfile filles with massages like: 
energyProducer506 unknown 
energyProducer507 unknown

included the IO Broker logfile.

[iobroker.current.txt](https://github.com/DrozmotiX/ioBroker.discovergy/files/6310418/iobroker.current.txt)

**Versions:**  
 - Adapter version: 0.5.4
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: Pasoberry Pi OS

**Comment by DutchmanNL** [comment]
still the case with 0.5.8 ?

**Comment by Illaren** [comment]
Hey,

Its still not working.

Screenshot Provided:

Greetings from Bavaria

Bastian

Am 17.08.2021 um 16:08 schrieb Dutchman:
