### ISSUE TITLE
unknown values

### ISSUE THREAD

**Issue by agerdes123** [DrozmotiX/ioBroker.discovergy#209]
Hi.
As advised in the iobroker log, here are some unknown values, the device is sending to the adapter.
Thanks in advance.

<html>
<body>

host.pi4-iobroker | 2021-06-30 18:23:41.530 | info | "system.adapter.discovergy.0" disabled
-- | -- | -- | --
discovergy.0 | 2021-06-30 18:23:40.540 | error | (24616) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 232100
discovergy.0 | 2021-06-30 18:23:40.540 | error | (24616) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 232900
discovergy.0 | 2021-06-30 18:23:40.538 | error | (24616) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 232500
discovergy.0 | 2021-06-30 18:23:40.537 | error | (24616) State type : phase3Power unknown, send this information to the developer ==> phase3Power : -1846810
discovergy.0 | 2021-06-30 18:23:40.536 | error | (24616) State type : phase1Power unknown, send this information to the developer ==> phase1Power : -1838840
discovergy.0 | 2021-06-30 18:23:40.532 | error | (24616) State type : phase2Power unknown, send this information to the developer ==> phase2Power : -1885850
discovergy.0 | 2021-06-30 18:23:40.397 | error | (24616) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 234200
discovergy.0 | 2021-06-30 18:23:40.397 | error | (24616) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 233300
discovergy.0 | 2021-06-30 18:23:40.396 | error | (24616) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 235000
discovergy.0 | 2021-06-30 18:23:40.395 | error | (24616) State type : phase3Power unknown, send this information to the developer ==> phase3Power : 437840
discovergy.0 | 2021-06-30 18:23:40.394 | error | (24616) State type : phase1Power unknown, send this information to the developer ==> phase1Power : -272410
discovergy.0 | 2021-06-30 18:23:40.391 | error | (24616) State type : phase2Power unknown, send this information to the developer ==> phase2Power : -268220
discovergy.0 | 2021-06-30 18:23:30.182 | error | (24616) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 232100
discovergy.0 | 2021-06-30 18:23:30.181 | error | (24616) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 232900
discovergy.0 | 2021-06-30 18:23:30.181 | error | (24616) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 232500
discovergy.0 | 2021-06-30 18:23:30.180 | error | (24616) State type : phase3Power unknown, send this information to the developer ==> phase3Power : -1846810
discovergy.0 | 2021-06-30 18:23:30.179 | error | (24616) State type : phase1Power unknown, send this information to the developer ==> phase1Power : -1838840
discovergy.0 | 2021-06-30 18:23:30.177 | error | (24616) State type : phase2Power unknown, send this information to the developer ==> phase2Power : -1885850
discovergy.0 | 2021-06-30 18:23:30.008 | error | (24616) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 234200
discovergy.0 | 2021-06-30 18:23:30.007 | error | (24616) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 233300
discovergy.0 | 2021-06-30 18:23:30.006 | error | (24616) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 235000
discovergy.0 | 2021-06-30 18:23:30.005 | error | (24616) State type : phase3Power unknown, send this information to the developer ==> phase3Power : 437840
discovergy.0 | 2021-06-30 18:23:30.004 | error | (24616) State type : phase1Power unknown, send this information to the developer ==> phase1Power : -272410
discovergy.0 | 2021-06-30 18:23:30.001 | error | (24616) State type : phase2Power unknown, send this information to the developer ==> phase2Power : -268220
discovergy.0 | 2021-06-30 18:23:19.719 | error | (24616) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 232100
discovergy.0 | 2021-06-30 18:23:19.719 | error | (24616) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 232900
discovergy.0 | 2021-06-30 18:23:19.718 | error | (24616) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 232500
discovergy.0 | 2021-06-30 18:23:19.717 | error | (24616) State type : phase3Power unknown, send this information to the developer ==> phase3Power : -1846810
discovergy.0 | 2021-06-30 18:23:19.715 | error | (24616) State type : phase1Power unknown, send this information to the developer ==> phase1Power : -1838840
discovergy.0 | 2021-06-30 18:23:19.713 | error | (24616) State type : phase2Power unknown, send this information to the developer ==> phase2Power : -1885850
discovergy.0 | 2021-06-30 18:23:19.580 | error | (24616) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 234200
discovergy.0 | 2021-06-30 18:23:19.580 | error | (24616) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 233300
discovergy.0 | 2021-06-30 18:23:19.579 | error | (24616) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 235000
discovergy.0 | 2021-06-30 18:23:19.579 | error | (24616) State type : phase3Power unknown, send this information to the developer ==> phase3Power : 437840
discovergy.0 | 2021-06-30 18:23:19.577 | error | (24616) State type : phase1Power unknown, send this information to the developer ==> phase1Power : -272410
discovergy.0 | 2021-06-30 18:23:19.574 | error | (24616) State type : phase2Power unknown, send this information to the developer ==> phase2Power : -268220
discovergy.0 | 2021-06-30 18:23:09.645 | error | (24616) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 232100
discovergy.0 | 2021-06-30 18:23:09.644 | error | (24616) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 232900
discovergy.0 | 2021-06-30 18:23:09.595 | error | (24616) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 232500
discovergy.0 | 2021-06-30 18:23:09.594 | error | (24616) State type : phase3Power unknown, send this information to the developer ==> phase3Power : -1846810
discovergy.0 | 2021-06-30 18:23:09.585 | error | (24616) State type : phase1Power unknown, send this information to the developer ==> phase1Power : -1838840
discovergy.0 | 2021-06-30 18:23:09.483 | error | (24616) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 234300
discovergy.0 | 2021-06-30 18:23:09.482 | error | (24616) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 234200
discovergy.0 | 2021-06-30 18:23:09.474 | info | (24616) All meters initialized, polling data every 10 seconds
discovergy.0 | 2021-06-30 18:23:09.472 | error | (24616) State type : phase2Power unknown, send this information to the developer ==> phase2Power : -1885850
discovergy.0 | 2021-06-30 18:23:09.467 | error | (24616) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 234300
discovergy.0 | 2021-06-30 18:23:09.467 | error | (24616) State type : phase3Power unknown, send this information to the developer ==> phase3Power : 408370
discovergy.0 | 2021-06-30 18:23:09.415 | error | (24616) State type : phase1Power unknown, send this information to the developer ==> phase1Power : -276570
discovergy.0 | 2021-06-30 18:23:09.349 | error | (24616) State type : phase2Power unknown, send this information to the developer ==> phase2Power : -284970
discovergy.0 | 2021-06-30 18:23:09.228 | info | (24616) All meters associated to your account discovered, initialise meters
discovergy.0 | 2021-06-30 18:23:08.092 | info | (24616) Discovergy Adapter startet, trying to discover meters associated with your account
discovergy.0 | 2021-06-30 18:23:08.061 | info | (24616) starting. Version 0.5.4 in /opt/iobroker/node_modules/iobroker.discovergy, node: v10.20.1
host.pi4-iobroker | 2021-06-30 18:23:06.553 | info | instance system.adapter.discovergy.0 started with pid 24616
host.pi4-iobroker | 2021-06-30 18:23:06.537 | info | "system.adapter.discovergy.0" enabled

</body>
</html>

**Comment by DutchmanNL** [comment]
hmm interesting all of them are defined, can you please try 0.5.7 ?

**Comment by DutchmanNL** [comment]
Solved in 0.5.8
