### ISSUE TITLE
Some Values are not logable by the adapter

### ISSUE THREAD

**Issue by mikethebman** [DrozmotiX/ioBroker.discovergy#212]
Hi I have installed the adapter, now when I start it i get this log, see attached. There are some values not able to log

I have a solar System from enpal i have got the discovenergy account from them.
[iobroker.current.log](https://github.com/DrozmotiX/ioBroker.discovergy/files/7225622/iobroker.current.log)

I hope you can help, thank you Mike!!!

**Comment by DutchmanNL** [comment]
Solved in 0.5.8 available in stable this Week
