### ISSUE TITLE
printedFullSerialNumber unknown

### ISSUE THREAD

**Issue by e-i-k-e** [DrozmotiX/ioBroker.discovergy#214]
Hallo,
habe heute den folgenden error im log gehabt.

(921) State type : printedFullSerialNumber unknown, send this information to the developer ==> printedFullSerialNumber : "1ESYxxxxxx"

Version 0.5.8 ist installiert. 
js-controller: 3.3.18

**Comment by hyperbit00** [comment]
kann dieses Verhalten bestätigen

"State type : printedFullSerialNumber unknown, send this information to the developer ==> printedFullSerialNumber : "1ESY1XX"


- Plattform linux
- Betriebssystem linux
- Architektur x64
- Node.js v12.22.1 (Es gibt eine neuere Version: v12.22.9 - Empfohlene Version v14.18.3)
- NPM 6.14.12

**Comment by Familienvater** [comment]
ich habe auch so eine Fehlermeldung:
State type : printedFullSerialNumber unknown, send this information to the developer ==> printedFullSerialNumber : "1ESY1xxxxxxxxx"

- Plattform linux
- Betriebssystem linux
- Architektur x64
- CPUs 2
- Geschwindigkeit 3696 MHz
- Modell Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz
- RAM 3.85 GB
- System-Betriebszeit 10 T. 19:53:47
- Node.js v12.22.10 (Es gibt eine neuere Version: v12.22.11 - Empfohlene Version v14.19.1)
- NPM 6.14.16
