### ISSUE TITLE
Timestamp im LastReading

### ISSUE THREAD

**Issue by kleinjn** [DrozmotiX/ioBroker.discovergy#215]

**Comment by kleinjn** [comment]
ES fehlt ein Timestamp im Objektbaum für die ausgelesenen Werte für 'lastreading'. Der timestamp wird zwar mitgeliefert aber nicht im Objektbaum gespeichert:

{"time":1641879030950,"values":{"power":144620,"power3":86070,"energyOut":292749764000,"power1":13360,"energy":71331567821000,"power2":45190}}

Dieser timestamp ist wichtig da die Discovergy Server manchmal einen Schluckauf haben und dann während Stunden (so wie am 10.1.2022) keine Daten liefern. Nach dem der Schluckauf abgeklungen ist werden die Daten in schneller Reihenfolge nachgeliefert. Ohne diesen timestamp ist dann keine Zuordung der Werte/Zeit mehr möglich. Diese Zuordnung ist sehr wichtig zb bei stündlichen Tarifen von awattar oder tiber.

Wäre es möglich diesen timestamp in den Objektbaum einzufügen ?

Vielen Dank im Voraus

**Comment by DutchmanNL** [comment]
habs ml auf die snelle und blind hinzugefügt, teste bitte mal die 0.5.9-0 (ur ueber git installierbar)
wen das klappt mache ich ne neue version die aus dem admin installiert werden kan

https://github.com/DrozmotiX/ioBroker.discovergy/commit/d8f81e91db78c2e01425526caa370a47df7c5745

**Comment by kleinjn** [comment]
Hallo, krieg den Adapter nicht von Github installiert:



host.ubuntu | 2022-01-12 13:08:03.707 | info | iobroker exit 0
-- | -- | -- | --
host.ubuntu | 2022-01-12 13:08:02.550 | info | iobroker upload [0] discovergy.admin  /opt/iobroker/node_modules/iobroker.discovergy/admin/Discovergy_logo.png  Discovergy_logo.png image/png
host.ubuntu | 2022-01-12 13:08:02.486 | info | iobroker upload [1] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/admin.d.ts admin.d.ts video/mp2t
host.ubuntu | 2022-01-12 13:08:02.421 | info | iobroker upload [2] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/button.png button.png image/png
host.ubuntu | 2022-01-12 13:08:02.357 | info | iobroker upload [3] discovergy.admin  /opt/iobroker/node_modules/iobroker.discovergy/admin/discovergy.png  discovergy.png image/png
host.ubuntu | 2022-01-12 13:08:02.293 | info | iobroker upload [4] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/index_m.html index_m.html text/html
host.ubuntu | 2022-01-12 13:08:02.228 | info | iobroker upload [5] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/style.css style.css text/css
host.ubuntu | 2022-01-12 13:08:02.116 | info | iobroker upload [6] discovergy.admin  /opt/iobroker/node_modules/iobroker.discovergy/admin/words.js words.js  application/javascript
host.ubuntu | 2022-01-12 13:08:02.050 | info | iobroker npm ERR! A complete log of this run can be found in:npm ERR!      /home/iobroker/.npm/_logs/2022-01-12T12_08_02_035Z-debug.log
host.ubuntu | 2022-01-12 13:08:02.047 | info | iobroker
host.ubuntu | 2022-01-12 13:08:02.026 | info | iobroker npm ERR! error: pathspec 'master' did not match any file(s) known to gitnpm ERR!
host.ubuntu | 2022-01-12 13:08:02.023 | info | iobroker npm ERR! Command failed: git checkout master
host.ubuntu | 2022-01-12 13:08:01.950 | info | iobroker npm ERR! code 1
host.ubuntu | 2022-01-12 13:07:46.095 | info | iobroker npm install DrozmotiX/ioBroker.discovergy#master --prefix "/opt/iobroker" (System call)
host.ubuntu | 2022-01-12 13:07:46.092 | info | iobroker NPM version: 6.14.15
host.ubuntu | 2022-01-12 13:07:45.509 | info | iobroker install DrozmotiX/ioBroker.discovergy#master
host.ubuntu | 2022-01-12 13:07:43.634 | info | iobroker url "https://github.com/DrozmotiX/ioBroker.discovergy/tarball/master" discovergy --debug

Was mache ich falsch ?

**Comment by DutchmanNL** [comment]
> Hallo, krieg den Adapter nicht von Github installiert:

hmm kan den Fehler nicht reproduzieren, welche JS-controller und admin version verwendest du ?
Wie hast du es installiert ?

<img width="987" alt="Schermafbeelding 2022-01-12 om 14 19 34" src="https://user-images.githubusercontent.com/7318445/149147957-287cd7f4-bff6-4359-af23-3d50dabdb3a9.png">

Resultat :
```
iobroker url DrozmotiX/ioBroker.discovergy --host ioBroker
install DrozmotiX/ioBroker.discovergy
NPM version: 6.14.15npm install DrozmotiX/ioBroker.discovergy --loglevel error --prefix "/opt/iobroker" (System call)
upload [6] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/words.js words.js application/javascript
upload [5] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/style.css style.css text/css
upload [4] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/index_m.html index_m.html text/html
upload [3] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/discovergy.png discovergy.png image/png
upload [2] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/button.png button.png image/png
upload [1] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/admin.d.ts admin.d.ts video/mp2t
upload [0] discovergy.admin /opt/iobroker/node_modules/iobroker.discovergy/admin/Discovergy_logo.png Discovergy_logo.png image/png
Process exited with code 0
```

**Comment by kleinjn** [comment]
Genauso wie in dem Bild

![image](https://user-images.githubusercontent.com/97591328/149150762-3c6241fb-bb61-4f5e-9023-05b322825cde.png)

Admin Version ist 5.2.3 Node-JS ist 14.18.2

**Comment by kleinjn** [comment]
Komplettes Log:

ubuntu@ubuntu:/home/iobroker/.npm/_logs$ cat 2022-01-12T13*.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'DrozmotiX/ioBroker.discovergy#master',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.2
4 verbose npm-session 51e054478fe59b05
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for github:DrozmotiX/ioBroker.discovergy#master Command failed: git checkout master
7 silly fetchPackageMetaData error: pathspec 'master' did not match any file(s) known to git
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 15658ms
10 verbose stack Error: Command failed: git checkout master
10 verbose stack error: pathspec 'master' did not match any file(s) known to git
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:383:12)
10 verbose stack     at ChildProcess.emit (events.js:400:28)
10 verbose stack     at maybeClose (internal/child_process.js:1058:16)
10 verbose stack     at Socket.<anonymous> (internal/child_process.js:443:11)
10 verbose stack     at Socket.emit (events.js:400:28)
10 verbose stack     at Pipe.<anonymous> (net.js:686:12)
11 verbose cwd /opt/iobroker
12 verbose Linux 5.4.0-1047-raspi
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "DrozmotiX/ioBroker.discovergy#master" "--prefix" "/opt/iobroker"
14 verbose node v14.18.2
15 verbose npm  v6.14.15
16 error code 1
17 error Command failed: git checkout master
17 error error: pathspec 'master' did not match any file(s) known to git
18 verbose exit [ 1, true ]

**Comment by DutchmanNL** [comment]
> Habes jetzt via URL https://github.com/DrozmotiX/ioBroker.discovergy installiert, das hat geklappt, timestamp stimmt auch

thanks ! dan mache ich spaeter ne release.... das mit dem admin teste ich mal local hatte selber 5.2.1

**Comment by DutchmanNL** [comment]
solved in v0.5.11
