### ISSUE TITLE
Fehlermeldungen beim Adapter

### ISSUE THREAD

**Issue by weindler** [DrozmotiX/ioBroker.discovergy#224]
Folgende Fehler erhalte ich beim Adapter.

`<html><body>

discovergy.0 | 2022-03-09 17:35:54.926 | error | State  type : printedFullSerialNumber unknown, send this information to the  developer ==> printedFullSerialNumber : "1EMH001015XXXX"
-- | -- | -- | --
discovergy.0 | 2022-03-09 17:35:54.669 | error | State  type : printedFullSerialNumber unknown, send this information to the  developer ==> printedFullSerialNumber : "1EMH001015XXXX"

</body>
</html>`

 Plattform linux Betriebssystem linux Architektur arm CPUs 4 Geschwindigkeit 1500 MHz Modell ARMv7 Processor rev 3 (v7l) RAM 3.8 GB System-Betriebszeit 00:09:30 Node.js v14.19.0 time 1646844221693 timeOffset -60 Anzahl der Adapter 400 NPM 6.14.16 js-controller 4.0.19

**Comment by TPPLordt** [comment]
Hi, 

I got the same error, the adapter don´t work. 
can somebody help?

discovergy version: 0.5.8
Plattform Raspberry pi 4 4GB

<html>
<body>


discovergy.0 | 4290 | 2022-07-24 11:41:55.305 | error | Unexpected end of JSON input
-- | -- | -- | -- | --
discovergy.0 | 4290 | 2022-07-24 11:41:55.304 | error | SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at Request._rp_callbackOrig (/opt/iobroker/node_modules/iobroker.discovergy/main.js:154:24) at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:76:39) at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (events.js:400:28) at Request.emit (domain.js:475:12) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at Request.emit (events.js:400:28) at Request.emit (domain.js:475:12)
discovergy.0 | 4290 | 2022-07-24 11:41:55.293 | error | unhandled promise rejection: Unexpected end of JSON input
discovergy.0 | 4290 | 2022-07-24 11:41:55.292 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
discovergy.0 | 4290 | 2022-07-24 11:41:55.232 | info | All meters associated to your account discovered, initialise meters
discovergy.0 | 4290 | 2022-07-24 11:41:54.867 | error | State type : printedFullSerialNumber unknown, send this information to the developer ==> printedFullSerialNumber : "1ESYxxxxxxxxxx"
discovergy.0 | 4290 | 2022-07-24 11:41:54.532 | error | State type : printedFullSerialNumber unknown, send this information to the developer ==> printedFullSerialNumber : "60xxxxxx_GENERATOR"


</body>
</html>

**Comment by DutchmanNL** [comment]
> I got the same error, the adapter don´t work.

its not exactly the same as your adapter crashes with "unhandled promise rejection: Unexpected end of JSON input".
can you please create a new issue for that and share a debug log?

**Comment by DutchmanNL** [comment]
solved in v0.5.11
