### ISSUE TITLE
Implement missing Data retrieval

### ISSUE THREAD

**Issue by zoernert** [DrozmotiX/ioBroker.discovergy#225]
**Describe wanted Enhancement !**  
Adapter retrieves data via polling. However if communication to the actual meter gets lost and recovers gaps need to be filled in history data. ( see [code](https://github.com/DrozmotiX/ioBroker.discovergy/blob/main/main.js#L132) )

**Why should we put effort in it ?**  
User [reports](https://forum.discovergy.com/t/keine-nachgelieferten-daten-ueber-die-api-bei-ausfall-am-23-3-2022/3265/6) usage from within a dynamic pricing environment. This will cause wrong calculations based on the provided data as actual consumption within the data gaps are not filled. 

**Additional context**

**Comment by DutchmanNL** [comment]
its to complexe/value of effort to retrieve historical data from API to be added to local data logging.
I'm sorry but that's a to specific case :)

If services failed, and data is missing I advice to retrieve it for that moment from Discovery web site and upload to your local database
