### ISSUE TITLE
Timelag between switch from 'Power consumption' to 'Power delivery'

### ISSUE THREAD

**Issue by kleinjn** [DrozmotiX/ioBroker.discovergy#236]
I do not know if the problem is related to the Discovergy API itself or to the adapter: 

I have a PV-Installation. When the PV produces more power than needed, the surplus goes to the grid and is accounted on the Discovergy meter as 'power delivery'. I takes between 30-50 seconds before the new value is delivered when power switches from 'power consumption' to 'power delivery' or vice-versa, even the update interval is set to 3 seconds. I have submitted this also to Discovergy as I do not know if the cause of this behavior is the API itself or the adapter. Could you please have a check?

**Comment by DutchmanNL** [comment]
Hi @kleinjn.. hmmm that would be an api issue as the data is not provided earlier.
Adapter request all data on API based on provided interval but indeed if the value are not easier available in API results the adapter shows previous data.

I think there is nothing I can do at adapter side but would be interested if you get any feedback from discovery about it

**Comment by DutchmanNL** [comment]
solved in v0.5.11
