### ISSUE TITLE
State type : printedFullSerialNumber unknown

### ISSUE THREAD

**Issue by skvarel** [DrozmotiX/ioBroker.discovergy#238]
![image](https://github.com/DrozmotiX/ioBroker.discovergy/assets/1114419/39488abc-78f3-4673-b422-d811c49d9f72)

**Comment by winnipuuh** [comment]
Perhabs the same issue for me Adapter crash cause of corrupted jason while there are two devices in the account:

<img width="1699" alt="image" src="https://github.com/DrozmotiX/ioBroker.discovergy/assets/442550/0845ade5-fe5e-4e87-9d4a-7f4ca38adc6d">
