### ISSUE TITLE
Error printedFullSerialNumber unknown / Connection lost to service or device - no error

### ISSUE THREAD

**Issue by Smallfeuer** [DrozmotiX/ioBroker.discovergy#241]
Since October i often lost connection. But that's a nother problem i hope. The Adapter often is not connectet to service or device. Restart helps. I lost lot of date, couse i get no error in log. Can you fix it, too?

`<html><body>

discovergy.0 | 2023-11-19 11:11:28.954 | info | All meters initialized, polling data every 30 seconds
-- | -- | -- | --
discovergy.0 | 2023-11-19 11:11:28.894 | info | All meters associated to your account discovered, initialise meters
discovergy.0 | 2023-11-19 11:11:28.694 | error | State  type : printedFullSerialNumber unknown, send this information to the  developer ==> printedFullSerialNumber : "1ESY1162041493"
discovergy.0 | 2023-11-19 11:11:28.551 | info | Discovergy Adapter startet, trying to discover meters associated with your account
discovergy.0 | 2023-11-19 11:11:28.507 | info | starting. Version 0.5.8 in /opt/iobroker/node_modules/iobroker.discovergy, node: v18.16.1, js-controller: 5.0.12
discovergy.0 | 2023-11-19 11:11:28.551 | info | Discovergy Adapter startet, trying to discover meters associated with your account
discovergy.0 | 2023-11-19 11:11:28.507 | info | starting. Version 0.5.8 in /opt/iobroker/node_modules/iobroker.discovergy, node: v18.16.1, js-controller: 5.0.12

</body>
</html>`

**Comment by DutchmanNL** [comment]
Van you please Tex Version 0.5.13? That should solche this issue

**Comment by Smallfeuer** [comment]
The Error is fixed in V0.5.14 Thanks. I hope this fix the other error (Connection lost), too.

`<html><body>

discovergy.0 | 2023-11-19 13:01:56.800 | info | All meters initialized, polling data every 30 seconds
-- | -- | -- | --
discovergy.0 | 2023-11-19 13:01:56.739 | info | All meters associated to your account discovered, initialise meters
discovergy.0 | 2023-11-19 13:01:56.322 | info | Discovergy Adapter startet, trying to discover meters associated with your account
discovergy.0 | 2023-11-19 13:01:56.303 | info | starting.  Version 0.5.14 (non-npm:  DrozmotiX/ioBroker.discovergy#1bf8b04000a644e761e806744bb552eaf6eb943a)  in /opt/iobroker/node_modules/iobroker.discovergy, node: v18.16.1,  js-controller: 5.0.12
discovergy.0 | 2023-11-19 13:01:52.557 | info | terminating


</body>
</html>`

**Comment by DutchmanNL** [comment]
> The Error is fixed in V0.5.14 Thanks. I hope this fix the other error (Connection lost), too.
> 
> 
> 
> `<html><body>
> 
> 
> 
> discovergy.0 | 2023-11-19 13:01:56.800 | info | All meters initialized, polling data every 30 seconds
> 
> -- | -- | -- | --
> 
> discovergy.0 | 2023-11-19 13:01:56.739 | info | All meters associated to your account discovered, initialise meters
> 
> discovergy.0 | 2023-11-19 13:01:56.322 | info | Discovergy Adapter startet, trying to discover meters associated with your account
> 
> discovergy.0 | 2023-11-19 13:01:56.303 | info | starting.  Version 0.5.14 (non-npm:  DrozmotiX/ioBroker.discovergy#1bf8b04000a644e761e806744bb552eaf6eb943a)  in /opt/iobroker/node_modules/iobroker.discovergy, node: v18.16.1,  js-controller: 5.0.12
> 
> discovergy.0 | 2023-11-19 13:01:52.557 | info | terminating
> 
> 
> 
> 
> 
> </body>
> 
> </html>`

Thank you conforming, I will review that version and push to stable this week
