### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by hengst12** [DrozmotiX/ioBroker.discovergy#244]
The address of the API was changed following the takeover of Discovergy by Inexogy.
Users, including myself, would certainly be grateful if the changes to the API were adopted.

Thank you for your work.

**Comment by DutchmanNL** [comment]
Is there any known documentation or just different APi UrL?

**Comment by DutchmanNL** [comment]
Found it, will have a look but also on holiday 😳

https://api.discovergy.com/docs/

**Comment by DutchmanNL** [comment]
@hengst12 scheint sich nur die Urkunde geändert zu haben, Probier mal bitte von git habe es geändert

**Comment by hengst12** [comment]
@DutchmanNL vielen Dank für schnelle Anpassung. Leider tut sich bei mir nichts (Version 0.5.14). Die Verbindung scheint da zu sein - connection steht auf true und die Instanz ist grün. Aber seit dem 12.08.24 um 01:15 Uhr keine Veränderung der Werte.

**Comment by hengst12** [comment]
Problem hat sich gelöst. Es lag nicht am Adapter, sondern am Zähler selbst. Der sendete keine Daten mehr. Ein Reset und schon funktioniert wieder alles wie gewohnt. Sorry 😕
