### ISSUE TITLE
Idee Awattar Hourly Tarif intigieren.

### ISSUE THREAD

**Issue by detafun** [DrozmotiX/ioBroker.discovergy#45]
Hallo,
ich glaube es gibt einige hier die bei Awattar Kunde sind. 
Der Tarif Hourly da aktuell ist.
Endpreis setzt sich aus Börenpreis + zusammen.
Gesamtpreis   19,91 + EPEX Spot DE + 0,250

Der EPEX Börsentarif kommt über die API. https://www.awattar.de/services/api

Ich bin dazu Programmier leihe, aber für einen Profi wohl kein Problem.

Wäre das möglich?

Dann könnte man es über VIS anzeigen lassen.

cu Detlef

**Comment by DutchmanNL** [comment]
hmm du meinst automatische abfrage dieser API nach jetzigen preis um diesen in die Berechnung ein zu calculieren ?

Das könnte man machen, frage ist hier oder im sourceanalytix adapter.

**Comment by detafun** [comment]
Ja genau! Damit man dann am Ende des Monats bereits seine Rechnung kennt. Oder besser sehen kann wo es hingeht.

**Comment by DutchmanNL** [comment]
sind dies variabele Tarife (also sprich Tagespreise) ?

ich muss mir mal die logic anschauen den wen die preise sich stündlich/täglich ändern hat das ja Auswirkungen auf die Berechnungen.
Zusätzlich muss der Adapter dan einige Sachen machen die eigentlich durch sourceanalytix übernommen werden könne. hmm... interessante Geschichte.

**Comment by DutchmanNL** [comment]
sind dies variabele Tarife (also sprich Tagespreise) ?

ich muss mir mal die logic anschauen den wen die preise sich stündlich/täglich ändern hat das ja Auswirkungen auf die Berechnungen.
Zusätzlich muss der Adapter dan einige Sachen machen die eigentlich durch sourceanalytix übernommen werden könne. hmm... interessante Geschichte.

**Comment by detafun** [comment]
Ja Stündlich und jeden Tag anders wie die Börse es hergibt. Daher der Feed mit den aktuellen Preisen.
Gesamtpreis 19,91 + EPEX Spot DE + 0,250

Der EPEX ist der Variable Stündliche Preis.

Wenn dann noch die Verküpfung und Ausrechnung mit den verbrauchten KW in der Stunde klappen würde, wäre es Bombe. Aber erste mal eines nach dem anderen.

**Comment by hotwin** [comment]
würde mich auch intressieren ob mann den preis auslesen kann da es bei awatar auch festpreise gibt

**Comment by detafun** [comment]
Das Projekt ist leider gerade etwas eingeschlafen. Ich denke das DutchmannNL derzeit wenig Zeit hat. Vielleicht kann er dennoch mal bitte ein kurzes Feedback geben.

**Comment by DutchmanNL** [comment]
hey thre, ys zuivel. baustellen ... ich schlage vor : 

- web-speedy beta veertig. machen
-  WLED erweitern
- dan dieses feature
- dan source analysis

schau ich mir am WE an hab diese we zeit naemlich (eh glaube ich )

**Comment by detafun** [comment]
Wie du es schaffen solltest, Wenn Fragen, dann schreiben :-)

**Comment by hotwin** [comment]
Sag einfach Bescheid

**Comment by Loni78** [comment]
Wenn der Tarif mit dabei wäre, wäre das super.......

**Comment by awattarpeter** [comment]
Hallo 

falls jemand Fragen oder andere (technische) Wünsche an uns (aWATTar) hat. Einfach melden. 

LG
Peter von aWATTar

**Comment by Landmilch71** [comment]
Das wäre wirklich super, wenn der Adapter auch mit den awattar (EPEX) Stundenpreisen umgehen könnte. Aufgepaßt: Die Gebühren(Netzentgelte, Steuern usw.) sind nicht fix. Sie hängen von der Postleitzahl ab. Man könnte aber auch einfach eine Variable hinterlegen, in die jeder User zur Konfiguration seine eigene Grundgebühr eintragen sollte. Ist sicher einfacher, als dieses dynamische Datenkonstrukt nachzubauen. Dieser Wert ändert eigentlich nur einmal im Jahr.

**Comment by apulanto** [comment]
Ich wäre auch sehr an einer solchen Integration interessiert. Gerade die Möglichkeit günstige Stunden zu nutzen, um z.B. die Waschmaschine vorzuprogrammieren oder die Tiefkühltruhe ein paar Grad vorkühlen zu lassen finde ich sehr interessant. Leider habe ich kein E-Auto, damit wäre der Spareffekt wohl am größten :)

**Comment by DutchmanNL** [comment]
hmm wie seht ihr das vor euh, ich habe da gerade so 0 plan was fuer infos wie wo herkommen und ich integrieren/kombinieren könnten.

Muestte man sich eventuell mal drüber austauschen ?

**Comment by detafun** [comment]
In der API von Awattar müste eigentlich alles zu holen sein. Und auf der Webseite steht, wie der Preis sich zusammen setzt.
https://www.awattar.de/tariffs/hourly
https://www.awattar.de/services/api

Hab im Moment wenig Zeit.

**Comment by Loni78** [comment]
Jeden Tag um 14.00 Uhr werden die Preise für die nächsten 24h bekannt gegeben. Die API müsste abgefragt werden und dann mit den Uhrzeiten in die ioBroker Objekte geschrieben werden z.B. 0:00 - 1:00 Uhr y EUR
01:00 - 2:00 Uhr x EUR.



Damit könnte man z.B. eine Wallbox, einen Speicher konfigurieren usw. Die historischen Preise würde ich persönlich nicht benötigen.

**Comment by DutchmanNL** [comment]
Ah jetzt verstehe ich danke 

Bin doch gerade noch am optimalisieren brauch man nen Account für api oder sind die Preise öffentlich 

Wo sollen sie hin ?

**Comment by Loni78** [comment]
Soweit ich weiss sind die Preise öffentlich. Unter dem Link 

https://www.awattar.de/services/api

findest Du viele Infos.

**Comment by Loni78** [comment]
Was noch toll wäre... Soweit sind die Preise in der API auf mWH (Megawatt) bezogen. Eine Umrechnung in kWH wäre auch noch hilfreich

**Comment by Landmilch71** [comment]
Am besten wäre ein eigener Adapter, der einmal täglich um 14:00 Uhr per Request die 24 Preise des Folgetages holen würde und in eine eigene Instanz mit eigenen Objekten ablegt. Ungefähr so:
awattar.de.tomorrow.dayname
awattar.de.tomorrow.date
awattar.de.tomorrow.Hour.00.marketprice
awattar.de.tomorrow.Hour.01.marketprice
awattar.de.tomorrow.Hour.02.marketprice
usw.
Um 0:00 Uhr werden täglich die Daten dann von tomorrow auf today verschoben.
awattar.de.today.dayname
awattar.de.today.date
awattar.de.today.date.Hour.00.marketprice
awattar.de.today.date.Hour.01.marketprice
awattar.de.today.date.Hour.02.marketprice
Und um 14:00 Uhr des Folgetages fängt alles wieder von vorne an.
Ist das ein großer Aufwand. Kann ich da helfen? Hab leider keine Ahnung wie ein Adapter erstellt wird.

**Comment by DutchmanNL** [comment]
> Ist das ein großer Aufwand. Kann ich da helfen? Hab leider keine Ahnung wie ein Adapter erstellt wird.

Ich wette mit dir, das wen du aktiv an meiner video reihe mitmachst du diesen adapter (nach der reihe) in 2-3 Abende gebaut hast :)

Es ist eigentlich eine simple JSON api abfrage, genau diese USE case werden ich in meiner 10-teiligen reihe (10-25 min Videos) detailliert behandeln

Zusaetlich, wen du lust haste, lade ich dich gerne in ein Webex team ein um aktieff zu unterstützen

https://forum.iobroker.net/topic/32265/das-project-einen-adapter-bauen-ist-nicht-schwer

**Comment by sirjojo69** [comment]
hi, ich bin ziemlich neu hier, bin aber auch awattar kunde und habe den entsprechenden adapter entwickelt. wer lust hat ihn zu testen... feel free.
https://github.com/sirjojo69/ioBroker.awattar
Bin natürlich auch offen für features und fehler...

**Comment by ElDiablo1985** [comment]
@sirjojo69 vielen Dank für dein Plugin.

Ich habe sogut wie eine frische Installation von IOBroker auf dem Raspberry. Wenn ich aber "npm i iobroker.awattar" bei Putty in der Konsole eingebe, bekomme ich folgende Fehlermeldung:

npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ iobroker.awattar@1.0.4
updated 1 package and audited 80 packages in 3.17s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Wenn ich "npm fund" eingebe, bekomme ich folgende Meldung:


/home/pi
├─┬ https://github.com/sponsors/feross
│ └── safe-buffer@5.2.1
├─┬ https://www.patreon.com/feross
│ └── safe-buffer@5.2.1
├─┬ https://feross.org/support
│ └── safe-buffer@5.2.1
└─┬ https://github.com/sponsors/epoberezkin
  └── ajv@6.12.6


Hast du ein Tipp für mich ? 

Scheint zumindest bei mir nicht wirklich zu funktionieren. 

Danke :)

**Comment by sirjojo69** [comment]
> 
> 
> @sirjojo69 vielen Dank für dein Plugin.
> 
> Ich habe sogut wie eine frische Installation von IOBroker auf dem Raspberry. Wenn ich aber "npm i iobroker.awattar" bei Putty in der Konsole eingebe, bekomme ich folgende Fehlermeldung:
> 
> npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
> npm WARN pi No description
> npm WARN pi No repository field.
> npm WARN pi No README data
> npm WARN pi No license field.
> 
>     * iobroker.awattar@1.0.4
>       updated 1 package and audited 80 packages in 3.17s
> 
> 
> 2 packages are looking for funding
> run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> Wenn ich "npm fund" eingebe, bekomme ich folgende Meldung:
> 
> /home/pi
> ├─┬ https://github.com/sponsors/feross
> │ └── safe-buffer@5.2.1
> ├─┬ https://www.patreon.com/feross
> │ └── safe-buffer@5.2.1
> ├─┬ https://feross.org/support
> │ └── safe-buffer@5.2.1
> └─┬ https://github.com/sponsors/epoberezkin
> └── ajv@6.12.6
> 
> Hast du ein Tipp für mich ?
> 
> Scheint zumindest bei mir nicht wirklich zu funktionieren.
> 
> Danke :)

hi... ich setz mir morgen mal ne frische iobroker vm auf und versuche das mal nachzuvollziehen. hast du es auch über den admin versucht? adapter aus github hinzufügen?

**Comment by ElDiablo1985** [comment]
> > @sirjojo69 vielen Dank für dein Plugin.
> > Ich habe sogut wie eine frische Installation von IOBroker auf dem Raspberry. Wenn ich aber "npm i iobroker.awattar" bei Putty in der Konsole eingebe, bekomme ich folgende Fehlermeldung:
> > npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
> > npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
> > npm WARN pi No description
> > npm WARN pi No repository field.
> > npm WARN pi No README data
> > npm WARN pi No license field.
> > ```
> > * iobroker.awattar@1.0.4
> >   updated 1 package and audited 80 packages in 3.17s
> > ```
> > 
> > 
> > 2 packages are looking for funding
> > run `npm fund` for details
> > found 0 vulnerabilities
> > Wenn ich "npm fund" eingebe, bekomme ich folgende Meldung:
> > /home/pi
> > ├─┬ https://github.com/sponsors/feross
> > │ └── safe-buffer@5.2.1
> > ├─┬ https://www.patreon.com/feross
> > │ └── safe-buffer@5.2.1
> > ├─┬ https://feross.org/support
> > │ └── safe-buffer@5.2.1
> > └─┬ https://github.com/sponsors/epoberezkin
> > └── ajv@6.12.6
> > Hast du ein Tipp für mich ?
> > Scheint zumindest bei mir nicht wirklich zu funktionieren.
> > Danke :)
> 
> hi... ich setz mir morgen mal ne frische iobroker vm auf und versuche das mal nachzuvollziehen. hast du es auch über den admin versucht? adapter aus github hinzufügen?

Keine Ahnung was man da genau machen muss. Bisher habe ich nur die Plugins über die interne Liste hinzufügen könenn. 
Plugins über Konsole ist mir neu. Habe mich halt auf die Kommando ebene per Putty eingelogt beim Raspberry und die Installationszeile oben eingegeben. 
Über NPM habe ich irgendwie ne art Install gemacht wo Readme, beschreibung usw... abgefragt und eingegeben werden musste bzw. abgefragt wird und die Meldung kommt gerade nicht mehr. 

Aktuell sieht es folgend aus ...

+ iobroker.awattar@1.0.4
updated 1 package and audited 126 packages in 6.629s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Aber das Plugin ist trotzdem nicht im iobroker zu finden.

**Comment by detafun** [comment]
Installiere direkt von Git über die Katze

**Comment by ElDiablo1985** [comment]
> Installiere direkt von Git über die Katze

Wären Sie so nett mir zu sagen wie ich es am besten mache ? 

Auf der Installationsseite stand rechts oben der Installationspfad. Also denn ich oben auch angegeben habe. 

Über Git und Katze das sagt mir leider nichts.

**Comment by ElDiablo1985** [comment]
Habe gegooglelt. Die Katze die bei Iobroker zu finden ist unter Adapter. Ok.

**Comment by ElDiablo1985** [comment]
$ ./iobroker url "npm i iobroker.awattar"
install "npm
NPM version: 6.14.8
npm install "npm --loglevel error --prefix "/opt/iobroker" (System call)
/bin/sh: 1: Syntax error: Unterminated quoted string
ERROR: host.IOBroker-Master Cannot install "npm: 2
ERROR: process exited with code 25

**Comment by ElDiablo1985** [comment]
Darf man fragen was mit "Start Threshold" und "End Threshold" gemeint ist ?
Unten bei Arbeitspreis ist es in Deutsch und oben in Englisch ? 

Bei Instanzen steht es in der Liste. 
Wo kann man die abgerufenen Daten denn einsehen ? Werden die nicht unter Objekte aufgeführt ? 
Zumindest ist unter Objekte nichts zu finden.

**Comment by sirjojo69** [comment]
> 
> 
> Darf man fragen was mit "Start Threshold" und "End Threshold" gemeint ist ?
> Unten bei Arbeitspreis ist es in Deutsch und oben in Englisch ?
> 
> Bei Instanzen steht es in der Liste.
> Wo kann man die abgerufenen Daten denn einsehen ? Werden die nicht unter Objekte aufgeführt ?
> Zumindest ist unter Objekte nichts zu finden.
> 
> Edit: Die Awattar information wird unter Objekte eingetragen nachdem einmal abgerufen wurde.

hmmm... damacht man sich die mühe für eine ausführliche readme seite und dann wird sie nicht gelesen ;-)
hier der auszug zu den beiden parametern:
In der "Start Threshold Loading (e.g. for EV)" steht eine Uhrzeit die den Beginn eines Zeitraumes darstellt, für den man die billigsten Stunden in geordneter Reihenfolge bekommen möchte
In der "End Threshold Loading" steht eine Uhrzeit die das Ende eines Zeitraumes darstellt, für den man die billigsten Stunden in geordneter Reihenfolge bekommen möchte

**Comment by DutchmanNL** [comment]
da es weber einen separaten adapter teleost ist wird ein integration hier nicht mehr weiter benötigt gehe ich von aus.
wen doch bitte reopen
