### ISSUE TITLE
one_hour

### ISSUE THREAD

**Issue by detafun** [DrozmotiX/ioBroker.discovergy#54]
Hallo,
es soll über die API abfragbar sein, also genau der Watt Wert der in der aktuellen Stunde verbraucht wurde.
Also   7 bis 8 Uhr   212 Watt,    8 bis 9 Uhr 1231 Watt etc...

Hier die Info von Disconvergy
"ja, kann man. Wenn es genau Stunden sein sollen, dann bitte als Resolution “ONE_HOUR” nehmen und den API Endpunkt “/readings” verwenden."

Kannst du das als Datenpunkt mit einbauen? 

cu Deta

**Comment by DutchmanNL** [comment]
ah ok danke ich verstehe was er meint schaue es mir an

**Comment by detafun** [comment]
Wäre cool, teste es gerne.

**Comment by detafun** [comment]
Schon mal geschaut?

**Comment by detafun** [comment]
Hallo, wäre mal schön ein kurzes Feedback von dir zu bekommen.

**Comment by DutchmanNL** [comment]
also man kann eine bestimmte Zeitspanne abfrage die frage ist was moechte man einbauen und wie.

eine Tabelle wo man Zeiten eingibt, ne feste zeit ?

<img width="1059" alt="Schermafbeelding 2020-04-17 om 23 03 32" src="https://user-images.githubusercontent.com/7318445/79613860-aadf5400-80ff-11ea-968c-b03b5e81221d.png">
https://api.discovergy.com/docs/

**Comment by DutchmanNL** [comment]
no response
