### ISSUE TITLE
Alten Zähler ausblenden

### ISSUE THREAD

**Issue by hlemken** [DrozmotiX/ioBroker.discovergy#84]
Hallo,

ich habe von Discovergy zwei Zähler und hatte vorher auch schon einen, der ausgebaut worden ist. Der alte Zähler liefert natürlich keine aktuellen Daten mehr, ist aber grundsätzlich sichtbar (z.B. im Web-Portal), damit ich die historischen Daten sehen kann. 

In dem Adapter ist er auch sichtbar und wird deshalb zyklisch mit abgefragt. Dies erzeugt dann immer  eine Fehlermeldung im Log: "(1433) Error retrieving information for : 60009385"

Deshalb ist mein Wunsch, konfigurieren zu können, welche Zähler abgefragt werden sollen und welche nicht.

Übrigens:  ich finde den Adapter super!

**Comment by DutchmanNL** [comment]
Hmm das lässt sich machen allgemein frage ich erst die Zähler ab und starte Dan einen Intervall auf die bestimmte id

Könnte mir vorstellen in der config diese Zähler wählbar zu machen 

So was in der Art ?

**Comment by hlemken** [comment]
Klingt gut. Das sollte das Problem lösen.

btw. die Warnungen "This value will not be set in future versions" die der Adapter im Moment bei jedem Abruf auslöst, sind wahrscheinlich bekannt, oder?

**Comment by winnipuuh** [comment]
Hallo seit dem crash von Discovergy funktioniert der Adapter nicht mehr, da er den "alten" Zähler abfragt dort aber nur eine ungültige (leere) jason zurückgemeldet wird.
Ist es sehr aufwendig den Adapter wie oben schon beschrieben nur mit einer Zählerid abzufragen?

LG
Gregor

**Comment by DutchmanNL** [comment]
@winnipuuh @hlemken where es moeglich mal Zugang zu euren login zu haben damit ich mir die daten Struktur anschauen kann ?


da es mehrere abfragen sind, die zählen und dan die werte, kan ich definitief einbauen das man einen ignoriert.
benötige aber daten zu programmieren/testen da ich selber keinen Zugang habe :)

**Comment by DutchmanNL** [comment]
habe bemerkt das der adapter auch gecrasht ist wen daten von einem Zähler fehlen, dies sollte in v0.5.11 behoben sein

**Comment by hkcrainer** [comment]
Es besteht aber noch das Problem mit alten Zählern, die im Benutzer bei Discovergy hinterlegt sind.
Der Adapter legt automatisch alle bekannten Zähler an und wirft jede Sekunde eine Fehlermeldung über die nicht Verfügbarkeit von den älteren, nicht aktuellen Zähler.
[doDiscovergyMeter Response] Error retrieving information for : 72a7dea4156e48a19b3b36xxxxxxxxxx

**Comment by DutchmanNL** [comment]
> Es besteht aber noch das Problem mit alten Zählern, die im Benutzer bei Discovergy hinterlegt sind. Der Adapter legt automatisch alle bekannten Zähler an und wirft jede Sekunde eine Fehlermeldung über die nicht Verfügbarkeit von den älteren, nicht aktuellen Zähler. [doDiscovergyMeter Response] Error retrieving information for : 72a7dea4156e48a19b3b36xxxxxxxxxx

sobald ich Zugang habe zu daten, siehe diese frage : 

> @winnipuuh @hlemken where es moeglich mal Zugang zu euren login zu haben damit ich mir die daten Struktur anschauen kann ?

kan ich die Fehlermeldung ausbauen das ignorieren eines nicht mehr anwesenden zahelers implementieren :)

**Comment by DutchmanNL** [comment]
@hkcrainer danke fuer die Zugangsdaten, bitte version 0.5.12 testen darin sollte jetzt Geräte die keine werte liefern komplett ignoriert werden

**Comment by hlemken** [comment]
Hallo zusammen,

 

entschuldigt bitte, dass ich mich erst jetzt melde. 

Ich benutze den Adapter wegen der Probleme mit dem alten Zähler schon lange nicht mehr sondern gehe direkt über Node-Red. Da das sehr stabil läuft, werde ich das so erstmal beibehalten. 

 

Viel Erfolg

Hubertus

 

Von: Rafal Drozda ***@***.***> 
Gesendet: Freitag, 27. Oktober 2023 23:45
An: DrozmotiX/ioBroker.discovergy ***@***.***>
Cc: hlemken ***@***.***>; Mention ***@***.***>
Betreff: Re: [DrozmotiX/ioBroker.discovergy] Alten Zähler ausblenden (#84)

 

@winnipuuh <https://github.com/winnipuuh>  @hlemken <https://github.com/hlemken>  where es moeglich mal Zugang zu euren login zu haben damit ich mir die daten Struktur anschauen kann ?

da es mehrere abfragen sind, die zählen und dan die werte, kan ich definitief einbauen das man einen ignoriert.
benötige aber daten zu programmieren/testen da ich selber keinen Zugang habe :)

**Comment by hkcrainer** [comment]
Issue wurde vollständig von @DutchmanNL behoben. Aus Anwendersicht läuft es mit der Version 0.5.12.

Vielen Dank!

**Comment by DutchmanNL** [comment]
> Issue wurde vollständig von @DutchmanNL behoben. Aus Anwendersicht läuft es mit der Version 0.5.12.
> 
> Vielen Dank!

perfect, dan cache ich hier mal zu :)
